In [1]:
#import the libraries

import numpy as np
import matplotlib.pyplot as plt

In [2]:
#create a list
a=[[11,12,13],[21,22,23],[31,32,33]]

In [3]:
#convert to numpy array
A=np.array(a)
A

array([[11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

In [4]:
#get the dimension of array
A.ndim

2

In [5]:
#gets the shape of array
A.shape

(3, 3)

In [6]:
#gets the size of array
A.size

9

In [7]:
#gets element first row second column
A[1][2]

23

In [8]:
#gets element first row second column in a diff format
A[1,2]

23

In [9]:
#gets element first row first column
A[0,0]

11

In [10]:
#gets element first row 0-2 column values
A[0][0:3]

array([11, 12, 13])

In [11]:
#gets element second row 0-2 column values
A[1][0:3]

array([21, 22, 23])

In [20]:
#gets element 0-2 row second column values
A[0:3][1]

array([21, 22, 23])

In [19]:
#gets element 0-2 row first column value
A[0:3][0]

array([11, 12, 13])

In [22]:
A[0:3][2]

array([31, 32, 33])

In [15]:
#addition of 2 numpy array
x=np.array([[1,0],[0,1]])
y=np.array([[2,1],[1,2]])
z=x+y
z

array([[3, 1],
       [1, 3]])

In [16]:
#multiplication of numpy array with 2
y=np.array([[2,1],[1,2]])
z=2*y
z

array([[4, 2],
       [2, 4]])

In [17]:
#multiplication of numpy array 
z=x*y
z

array([[2, 0],
       [0, 2]])

In [23]:
#dot product 2 arrays
d=np.array([[0,1,1],[1,0,1]])
e=np.array([[1,1],[0,1],[-1,1]])
f=np.dot(d,e)
f

array([[-1,  2],
       [ 0,  2]])

In [24]:
#estimating sin functions
np.sin(f)

array([[-0.84147098,  0.90929743],
       [ 0.        ,  0.90929743]])

In [26]:
#transponse of array e
e.T

array([[ 1,  0, -1],
       [ 1,  1,  1]])