In [1]:
#import nyumpy package
import numpy as np

In [2]:
#first numpy array
First_Numpy_Array=np.array([1,2,3,4,5])
First_Numpy_Array

array([1, 2, 3, 4, 5])

In [4]:
#creating zero numpy array
Zero_Numpy_Array=np.zeros([3,3])
Zero_Numpy_Array

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [5]:
#creating ones numpy array
Ones_Numpy_Array=np.ones([3,3])
Ones_Numpy_Array

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [7]:
#creating empty array
Empty_Numpy_Array=np.empty([2,4])
Empty_Numpy_Array

array([[0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000],
       [0.00000000e+000, 7.70742408e-321, 7.08746594e-312,
        7.08746594e-312]])

In [9]:
#array with arange method
array_arange=np.arange(12)
array_arange

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [16]:
#reshape the array
array_reshape=array_arange.reshape(3,4)
array_reshape

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [17]:
#linspace for linearly(equally) spaced elements
print(np.linspace(-2,2,6))

[-2.  -1.2 -0.4  0.4  1.2  2. ]


In [20]:
#1D array
one_dimensional_array=np.arange(15)
one_dimensional_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [21]:
#2D array
two_dimensional_array=one_dimensional_array.reshape(3,5)
two_dimensional_array

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [22]:
#3D array
three_dimensional_array=np.arange(27).reshape(3,3,3)
three_dimensional_array

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])