In [1]:
import numpy as np

In [18]:
new_nparray=np.array([[1,2,3,4,5,6],[6,7,8,9,10,11]])

In [19]:
#flattens the dataset
new_nparray.ravel()

array([ 1,  2,  3,  4,  5,  6,  6,  7,  8,  9, 10, 11])

In [21]:
#reshapes the dataset to 3 rows 4 columns
new_nparray.reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  6,  7],
       [ 8,  9, 10, 11]])

In [24]:
#resizes again to 2 rows 6 columns
new_nparray.resize(2,6)
new_nparray

array([[ 1,  2,  3,  4,  5,  6],
       [ 6,  7,  8,  9, 10, 11]])

In [26]:
#splits the array into 2
np.hsplit(new_nparray,2)

[array([[1, 2, 3],
        [6, 7, 8]]),
 array([[ 4,  5,  6],
        [ 9, 10, 11]])]

In [27]:
new_nparray1=np.array([1,2,3,4,5,6])
new_nparray2=np.array([7,8,9,10,11,12])

In [29]:
#stacks the arrays together
np.hstack((new_nparray1,new_nparray2))

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])